ci: fix python datafusion test (#5991)
Fixing error:

```
FAILED python/tests/test_table_provider.py::test_table_loading - ImportError: Incompatible libraries. DataFusion 52.0.0 introduced an incompatible signature change for table providers. Either downgrade DataFusion or upgrade your function library.
```